services:
  app:
    image: docker.io/library/php:8.2-apache
    container_name: exam6-app
    ports:
      - "8024:80"
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db
    networks:
      - exam6-net
    restart: unless-stopped
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql &&
             a2enmod rewrite &&
             apache2-foreground"

  db:
    image: docker.io/library/mysql:8.0
    container_name: exam6-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ujian_online
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      TZ: Asia/Makassar
    ports:
      - "3313:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:ro
      - exam6-dbdata:/var/lib/mysql:z
    networks:
      - exam6-net
    restart: unless-stopped

  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    container_name: exam6-pma
    ports:
      - "8025:80"
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - exam6-net
    restart: unless-stopped

volumes:
  exam6-dbdata:

networks:
  exam6-net:
    driver: bridge